services:
  - type: web
    name: christian-songs-app
    env: node
    region: ohio
    plan: free
    rootDir: christian-songs-app
    buildCommand: npm install && npm run build
    startCommand: npm start
